const baseUrl = 'https://integrationbackendulacit.azurewebsites.net';
export const logInUrl = `${baseUrl}/Session/Login`;
export const signUpUrl = `${baseUrl}/Session/SignUp`;
export const addMaterialUrl = `${baseUrl}/Material/AddMaterial`;
export const getAllMaterialsUrl = `${baseUrl}/Material/GetAllMaterials`;
export const updateMaterialUrl = `${baseUrl}/Material/EditMaterial`;
export const addToolUrl = `${baseUrl}/Tool/AddTool`;
export const getAllToolsUrl = `${baseUrl}/Tool/GetAllTools`;
export const addWorkerUrl = `${baseUrl}/Employee/AddEmployee`;
export const getAllWorkersUrl = `${baseUrl}/Employee/GetAllEmployes`;
export const getAllProductsUrl = `${baseUrl}/Product/GetAllProducts`;
export const getAddProductUrl = `${baseUrl}/Product/AddProduct`;
export const getProductionPlanningUrl = `${baseUrl}/Production/GetPlanning`;
export const getAllProductionsUrl = `${baseUrl}/Production/GetAllProductions`;
export const getAllProcessesUrl = `${baseUrl}/Process/GetAllProcesses`