const baseUrl = 'https://integrationbackendulacit.azurewebsites.net';
export const logInUrl = `${baseUrl}/Session/Login`;
export const signUpUrl = `${baseUrl}/Session/SignUp`;
export const addMaterialUrl = `${baseUrl}/Material/AddMaterial`;
export const addToolUrl = `${baseUrl}/Tool/AddTool`;
export const updateToolUrl = `${baseUrl}/Tool/UpdateTool`;
export const getAllMaterialsUrl = `${baseUrl}/Material/GetAllMaterial`;
export const getAllToolsUrl = `${baseUrl}/Tool/GetAllTool`;
export const getAllProductsUrl = `${baseUrl}/Product/GetAll`;